/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.module;

import com.libs.PlaceholderTextField;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javazoom.jl.player.Player;
import static com.module.formMain.dictionaryManagement;
import static com.module.formMain.topic;
import java.io.FileNotFoundException;
import java.io.IOException;
import javazoom.jl.decoder.JavaLayerException;
/**
 *
 * @author phixuanhoan
 */
public class formLearn extends javax.swing.JFrame {

    private int index               = 0;
    private int demClickDapAn       = 1;
    private boolean checkAnswer     = false;
    private String topicName        = new String();
    PlaceholderTextField txtAnswer  = new PlaceholderTextField("");
    String typeUser;
    String fullname;
    /**
     * Creates new form formTuVung
     * @param topic
     * @param typeUser
     * @param fullname
     */
    public formLearn(String topic, String typeUser, String fullname) {
        this.typeUser = typeUser;
        this.fullname = fullname;
        initComponents();
        areaWordInfo.setSize(800, 200);
        areaWordInfo.setLineWrap(true);
        areaWordInfo.setWrapStyleWord(true);
        areaWordInfo.setEditable(false);
        this.setLocationRelativeTo(null);
        lblTitle.setText("Chủ đề: " + topic);
        areaWordInfo.setText(cmsArea1(index));
        lblPagi.setText((index + 1) + "\\" + formMain.topic.listWordTopic.size());
        lblMessage.setVisible(false);
        topicName = topic;
        ImageIcon imageIcon = new ImageIcon("public/images_topic_word/" + topicName.trim() + "/" + formMain.topic.listWordTopic.get(index).getSpelling() + ".jpg");
        File apath = new File(imageIcon.toString());
        if (apath.exists()) {
            lblIcon.setIcon(imageIcon);
        } else {
            lblIcon.setIcon(new ImageIcon("public/bgr.jpg"));
        }
        //Ô textfield mới
        txtAnswer.setPlaceholder("Nhập đáp án vào đây !");
        final Font f = txtAnswer.getFont();
        txtAnswer.setFont(new Font(f.getName(), f.getStyle(), 18));
        txtAnswer.setLocation(16, 393);
        txtAnswer.setSize(360, 45);
        this.add(txtAnswer);

        txtAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyEnter(evt);
            }
        });
        
        //border
        lblIcon.setBorder(formMain.brdr_b);
        lblPagi.setBorder(formMain.brdr_s);
        lblTitle.setBorder(formMain.brdr_s);
        txtAnswer.setBorder(formMain.brdr_s);
        areaWordInfo.setBorder(formMain.brdr_b);

    }

    public String cmsArea1(int index) {
        String define = formMain.topic.listWordTopic.get(index).getDefine();
        String same = formMain.topic.listWordTopic.get(index).getSame();
        String tmp = "Định nghĩa : \n" + define + "\n\ntừ đồng nghĩa:\n" + same;
        return tmp;
    }

    public void keyEnter(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkResult();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        areaWordInfo = new javax.swing.JTextArea();
        lblPagi = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 415));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/audio1.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(204, 255, 204));
        btnResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/note_add32.png"))); // NOI18N
        btnResult.setText("Đáp án");
        btnResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/pre.png"))); // NOI18N
        btnBack.setText("   Quay lại");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(204, 255, 204));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/next.png"))); // NOI18N
        btnNext.setText("Tiếp theo   ");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chủ đề: felling");
        lblTitle.setToolTipText("");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTitle.setOpaque(true);

        areaWordInfo.setBackground(new java.awt.Color(255, 255, 204));
        areaWordInfo.setColumns(20);
        areaWordInfo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        areaWordInfo.setRows(5);

        lblPagi.setBackground(new java.awt.Color(204, 255, 204));
        lblPagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagi.setForeground(new java.awt.Color(0, 0, 153));
        lblPagi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagi.setText("1/20");
        lblPagi.setToolTipText("");
        lblPagi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPagi.setOpaque(true);

        btnCheck.setBackground(new java.awt.Color(204, 255, 204));
        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/accept.png"))); // NOI18N
        btnCheck.setText("Kiểm tra");
        btnCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/remove.png"))); // NOI18N
        lblMessage.setText("You are incorrect");

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setMaximumSize(new java.awt.Dimension(200, 200));
        lblIcon.setMinimumSize(new java.awt.Dimension(200, 200));
        lblIcon.setPreferredSize(new java.awt.Dimension(200, 200));

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(areaWordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218)
                                .addComponent(lblPagi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaWordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        String result = "";
        if (demClickDapAn % 2 != 0) {
            btnResult.setText("Ẩn đáp án");
            btnResult.setForeground(Color.red);
            demClickDapAn++;
            String spelling = formMain.topic.listWordTopic.get(index).getSpelling();
            String Explain = formMain.topic.listWordTopic.get(index).getExplain();
            String Tran = formMain.topic.listWordTopic.get(index).getTranscription();
            String type = formMain.topic.listWordTopic.get(index).getType();
            String example = formMain.topic.listWordTopic.get(index).getExample();
            String exExample = formMain.topic.listWordTopic.get(index).getExlainExample();

            result = areaWordInfo.getText() + "\n\nTừ:\n " + spelling + "   (" + type + ")  -  "
                    + Explain + "  -  " + Tran + "\nCâu ví dụ: \n" + example + "\nNghĩa câu ví dụ: \n" + exExample;
        } else {
            btnResult.setText("Đáp án");
            btnResult.setForeground(Color.black);
            demClickDapAn++;
            result = cmsArea1(index);
        }

        areaWordInfo.setText(result);
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        txtAnswer.setText("");
        if (index < formMain.topic.listWordTopic.size() - 1) {
            btnResult.setText("Đáp án");
            lblMessage.setVisible(false);
            btnResult.setForeground(Color.black);
            demClickDapAn = 1;
            index = index + 1;

            ImageIcon imageIcon = new ImageIcon("public/images_topic_word/" + topicName.trim() + "/" + formMain.topic.listWordTopic.get(index).getSpelling() + ".jpg");
            File apath = new File(imageIcon.toString());
            if (apath.exists()) {
                lblIcon.setIcon(imageIcon);
            } else {
                lblIcon.setIcon(new ImageIcon("public/bgr.jpg"));
            }
            areaWordInfo.setText(cmsArea1(index));
            lblPagi.setText((index + 1) + "\\" + formMain.topic.listWordTopic.size());
        } else {
            JOptionPane.showMessageDialog(null, "Đã hoàn thành topic !");
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        txtAnswer.setText("");
        if (index > 0) {
            btnResult.setText("Đáp án");
            lblMessage.setVisible(false);
            btnResult.setForeground(Color.black);
            index = index - 1;
            ImageIcon imageIcon = new ImageIcon("public/images_topic_word/" + topicName.trim() + "/" + formMain.topic.listWordTopic.get(index).getSpelling() + ".jpg");
            File apath = new File(imageIcon.toString());
            if (apath.exists()) {
                lblIcon.setIcon(imageIcon);
            } else {
                lblIcon.setIcon(new ImageIcon("public/bgr.jpg"));
            }
            demClickDapAn = 1;
            areaWordInfo.setText(cmsArea1(index));
            lblPagi.setText((index + 1) + "\\" + formMain.topic.listWordTopic.size());
        } else {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu !");
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = formMain.topic.listWordTopic.get(index).getSpelling().trim();
        try {
            Player play = new Player(formMain.Synthesiser.getMP3Data(name));
            play.play();
        } catch (IOException | JavaLayerException e) {
            JOptionPane.showMessageDialog(null, "Không có phát âm cho từ này");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //Play nhạc
    public void playMP3(String path) {
        try {
            FileInputStream fileMP3 = new FileInputStream(path);
            Player Player = new Player(fileMP3);
            Player.play();
        } catch (FileNotFoundException | JavaLayerException ex) {
            JOptionPane.showMessageDialog(null, "Không có phát âm cho từ này!");
        }
    }

    public void checkResult() {
        if (txtAnswer.getText().equals(formMain.topic.listWordTopic.get(index).getSpelling().trim())) {
            checkAnswer = true;
            lblMessage.setVisible(true);
            lblMessage.setForeground(Color.green);
            lblMessage.setIcon(new ImageIcon("public/accept.png"));
            lblMessage.setText("You are correct!");
            playMP3("public/correct.mp3");
        } else {
            lblMessage.setVisible(true);
            checkAnswer = false;
            lblMessage.setForeground(Color.red);
            lblMessage.setIcon(new ImageIcon("public/remove.png"));
            lblMessage.setText("You are incorrect!");
            playMP3("public/incorrect.mp3");
        }
    }
    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        checkResult();
    }//GEN-LAST:event_btnCheckActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SwingUtilities.invokeLater(() -> {
            System.out.print(typeUser);
            JFrame formMain = new formMain(typeUser, fullname);
            formMain.setVisible(true); //hiện giao diện 
        });
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaWordInfo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPagi;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
