/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ver_1;

import java.awt.Color;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jl.player.Player;
import static ver_1.formMain.Dictionary;
import static ver_1.formMain.Topic;

/**
 *
 * @author phixuanhoan
 */
public class formTuVung extends javax.swing.JFrame {
    private int index = 0;
    private int demClickDapAn = 1;
    private boolean checkAnswer = false;
//    private topic Topic = new topic();
    /**
     * Creates new form formTuVung
     */
    public formTuVung(String topic) {
        initComponents();
        this.setSize(850, 600);
        areaWordInfo.setSize(800, 200);
        areaWordInfo.setLineWrap(true);
        areaWordInfo.setWrapStyleWord(true);
        areaWordInfo.setEditable(false); 
        this.setLocationRelativeTo(null);
        lblTitle.setText("Chủ đề: " + topic);
        areaWordInfo.setText(cmsArea1(index));
        lblPagi.setText((index + 1) + "\\"+formMain.Topic.listWordTopic.size());
        lblMessage.setVisible(false);
        
    }
    public String cmsArea1(int index){
        String define = formMain.Topic.listWordTopic.get(index).getDefine();
        String same = formMain.Topic.listWordTopic.get(index).getSame();
        String tmp = "Định nghĩa : \n" + define + "\n\ntừ đồng nghĩa:\n" + same;
        return tmp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnswer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        areaWordInfo = new javax.swing.JTextArea();
        lblPagi = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 415));
        setPreferredSize(new java.awt.Dimension(851, 400));

        txtAnswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(204, 204, 204));
        txtAnswer.setText("Gõ từ vựng bạn đoán được ...");
        txtAnswer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtAnswerMouseMoved(evt);
            }
        });
        txtAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnswerMouseClicked(evt);
            }
        });
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/if_Audio_1891017.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(204, 255, 204));
        btnResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/note_add.png"))); // NOI18N
        btnResult.setText("Đáp án");
        btnResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/back.png"))); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(204, 255, 204));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/next.png"))); // NOI18N
        btnNext.setText("Tiếp theo");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 255, 204));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chủ đề: felling");
        lblTitle.setToolTipText("");
        lblTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitle.setOpaque(true);

        areaWordInfo.setBackground(new java.awt.Color(255, 255, 204));
        areaWordInfo.setColumns(20);
        areaWordInfo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        areaWordInfo.setRows(5);

        lblPagi.setBackground(new java.awt.Color(204, 255, 204));
        lblPagi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPagi.setForeground(new java.awt.Color(0, 0, 153));
        lblPagi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagi.setText("1/20");
        lblPagi.setToolTipText("");
        lblPagi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPagi.setOpaque(true);

        btnCheck.setBackground(new java.awt.Color(204, 255, 204));
        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/accept.png"))); // NOI18N
        btnCheck.setText("Kiểm tra");
        btnCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ver_1/images/remove.png"))); // NOI18N
        lblMessage.setText("You are incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(areaWordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCheck)
                                .addGap(35, 35, 35)
                                .addComponent(jButton1)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPagi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(areaWordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPagi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        String result = "";
        if(demClickDapAn % 2 !=0){
            btnResult.setText("Ẩn đáp án");
            btnResult.setForeground(Color.red);
            demClickDapAn++;
            String spelling = formMain.Topic.listWordTopic.get(index).getSpelling();
            String Explain = formMain.Topic.listWordTopic.get(index).getExplain();
            String Tran = formMain.Topic.listWordTopic.get(index).getTranscription();
            String type = formMain.Topic.listWordTopic.get(index).getType();
            String example = formMain.Topic.listWordTopic.get(index).getExample();
            String exExample = formMain.Topic.listWordTopic.get(index).getExlainExample();
        
            result = areaWordInfo.getText() + "\n\nTừ:\n " + spelling + "   ("+type+")  -  "
                        + Explain + "  -  " + Tran + "\n\nCâu ví dụ: \n" +example +"\n\nNghĩa câu ví dụ: \n" +exExample;
        }else{
            btnResult.setText("Đáp án");
            btnResult.setForeground(Color.black);
            demClickDapAn++;
            result = cmsArea1(index);
        }
        
        areaWordInfo.setText(result);
    }//GEN-LAST:event_btnResultActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(index < formMain.Topic.listWordTopic.size() -1){
            btnResult.setText("Đáp án");
            lblMessage.setVisible(false);
            btnResult.setForeground(Color.black);
            demClickDapAn = 1;
            index = index + 1;
            areaWordInfo.setText(cmsArea1(index));
            lblPagi.setText((index + 1) + "\\"+formMain.Topic.listWordTopic.size());
        }else{
            JOptionPane.showMessageDialog(null, "Không có dữ liệu !");
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(index >0){
            btnResult.setText("Đáp án");
            lblMessage.setVisible(false);
            btnResult.setForeground(Color.black);
            index = index - 1;
            demClickDapAn = 1;
            areaWordInfo.setText(cmsArea1(index));
            lblPagi.setText((index + 1) + "\\"+formMain.Topic.listWordTopic.size());
        }else{
            JOptionPane.showMessageDialog(null, "Không có dữ liệu !");
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            FileInputStream fileMP3 = new FileInputStream("tranTopic/" +
                                    formMain.Topic.listWordTopic.get(index).getSpelling().trim() + ".mp3");
            Player Player = new Player(fileMP3);
            Player.play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không có phát âm cho từ này!");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void txtAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnswerMouseClicked
        txtAnswer.setText("");
        txtAnswer.setForeground(Color.black);
    }//GEN-LAST:event_txtAnswerMouseClicked

    private void txtAnswerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnswerMouseMoved
        if(txtAnswer.getText().equals("")){
            txtAnswer.setText("Gõ từ bạn đoán được vào đây ... ");
            txtAnswer.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtAnswerMouseMoved

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if(txtAnswer.getText().equals(formMain.Topic.listWordTopic.get(index).getSpelling().trim())){
            checkAnswer = true;
            lblMessage.setVisible(true);
            lblMessage.setForeground(Color.green);
            lblMessage.setIcon(new ImageIcon("button/accept.png"));
            lblMessage.setText("You are correct!");
        }else{
            lblMessage.setVisible(true);
            checkAnswer = false;
            lblMessage.setForeground(Color.red);
            lblMessage.setIcon(new ImageIcon("button/remove.png"));
            lblMessage.setText("You are incorrect!");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTuVung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTuVung("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaWordInfo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPagi;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
